### ISSUE TITLE
Poor code quality

### ISSUE THREAD

**Issue by wizzlerr** [Szab/SO_VirtualMemory#3]
Please fix before next release as our PO requires good code quality and no or little technical debt.

@Szab

**Comment by Szab** [comment]
Hello,

thanks for the feedback! We always appreciate a bit of a constructive criticism!

Could you please point out pieces of code which might be problematic to understand by other programmers or/and which might cause some trouble performance-wise?

Thanks!

**Comment by wizzlerr** [comment]
Cool.
